name: Discord Bot Build Status

on:
  push:
    branches: [master]
    pull-request: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: NPM Install
        run: npm install
      - name: NODE CI
        run: npm ci
      - name: ESlint Checks
        run: npx eslint .
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag britta-bot:$(date +%s)
